"""Dynamic delivery policy.

The Core generates a DeliveryPolicy from the response seed. Delivery uses it to
control how the response lands: density, pacing, question behavior, humor,
certainty, warmth, and ending style.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal

from arche.laws import STATIC_LAW_IDS


class PacingProfile(str, Enum):
    CRISP = "crisp"
    CALM = "calm"
    GENTLE = "gentle"
    EXPRESSIVE = "expressive"


class EndingStyle(str, Enum):
    HARD_STOP = "hard_stop"
    SOFT_LANDING = "soft_landing"
    INVITATION = "invitation"
    ACTION_STEP = "action_step"


class CertaintyStyle(str, Enum):
    CONFIDENT = "confident"
    PROVISIONAL = "provisional"
    CAUTIOUS = "cautious"


QuestionType = Literal["none", "clarifying", "practical", "reflective", "relational"]


@dataclass(slots=True)
class QuestionPolicy:
    allowed: bool = False
    max_questions: int = 0
    question_type: QuestionType = "none"
    ask_only_if_blocked: bool = True


@dataclass(slots=True)
class DeliveryPolicy:
    """Moment-specific delivery rules generated by Core."""

    max_words: int = 220
    max_chars_per_beat: int = 280
    pacing_profile: PacingProfile = PacingProfile.CALM
    beat_pause_ms: int = 650
    typing_speed: Literal["slow", "medium", "fast"] = "medium"
    warmth_level: int = 4          # 0-9
    directness_level: int = 5      # 0-9
    humor_allowed: bool = False
    emotional_intensity: int = 3   # 0-9
    certainty_style: CertaintyStyle = CertaintyStyle.PROVISIONAL
    ending_style: EndingStyle = EndingStyle.HARD_STOP
    question_policy: QuestionPolicy = field(default_factory=QuestionPolicy)
    enforced_laws: frozenset[str] = field(default_factory=lambda: STATIC_LAW_IDS)

    def to_dict(self) -> dict:
        return {
            "max_words": self.max_words,
            "max_chars_per_beat": self.max_chars_per_beat,
            "pacing_profile": self.pacing_profile.value,
            "beat_pause_ms": self.beat_pause_ms,
            "typing_speed": self.typing_speed,
            "warmth_level": self.warmth_level,
            "directness_level": self.directness_level,
            "humor_allowed": self.humor_allowed,
            "emotional_intensity": self.emotional_intensity,
            "certainty_style": self.certainty_style.value,
            "ending_style": self.ending_style.value,
            "question_policy": {
                "allowed": self.question_policy.allowed,
                "max_questions": self.question_policy.max_questions,
                "question_type": self.question_policy.question_type,
                "ask_only_if_blocked": self.question_policy.ask_only_if_blocked,
            },
            "enforced_laws": sorted(self.enforced_laws),
        }


def build_delivery_policy(*, state: str, zone: str, mode: str, agent_signals: dict[str, float]) -> DeliveryPolicy:
    """Create a moment-specific policy from seed conditions.

    First pass: deterministic mapping. Later this can include Core confidence,
    user-specific preferences, and Whisperer weight trims.
    """
    policy = DeliveryPolicy()

    threat = agent_signals.get("threat", 0.0)
    social = agent_signals.get("social", 0.0)
    reason = agent_signals.get("reason", 0.0)
    reward = agent_signals.get("reward", 0.0)

    # Mode-level defaults.
    if mode in {"CLINICAL", "NORMAL"}:
        policy.pacing_profile = PacingProfile.CRISP
        policy.typing_speed = "fast"
        policy.beat_pause_ms = 350
        policy.max_chars_per_beat = 320
        policy.directness_level = 7
        policy.warmth_level = 3
        policy.ending_style = EndingStyle.HARD_STOP
    elif mode == "RELATIONAL":
        policy.pacing_profile = PacingProfile.GENTLE
        policy.typing_speed = "medium"
        policy.beat_pause_ms = 750
        policy.max_chars_per_beat = 220
        policy.warmth_level = 7
        policy.directness_level = 4
        policy.ending_style = EndingStyle.SOFT_LANDING
    elif mode == "EXPLORATORY":
        policy.pacing_profile = PacingProfile.EXPRESSIVE
        policy.typing_speed = "medium"
        policy.beat_pause_ms = 550
        policy.max_chars_per_beat = 360
        policy.question_policy = QuestionPolicy(True, 1, "clarifying", True)
        policy.ending_style = EndingStyle.ACTION_STEP
    elif mode == "PROTECTIVE":
        policy.pacing_profile = PacingProfile.GENTLE
        policy.typing_speed = "slow"
        policy.beat_pause_ms = 900
        policy.max_chars_per_beat = 180
        policy.max_words = 140
        policy.warmth_level = 5
        policy.directness_level = 6
        policy.emotional_intensity = 2
        policy.certainty_style = CertaintyStyle.CAUTIOUS
        policy.ending_style = EndingStyle.SOFT_LANDING

    # State/zone modifiers.
    if zone == "mobilized" or threat > 0.55:
        policy.humor_allowed = False
        policy.max_words = min(policy.max_words, 180)
        policy.question_policy = QuestionPolicy(False, 0, "none", True)
        policy.certainty_style = CertaintyStyle.CAUTIOUS
        policy.directness_level = max(policy.directness_level, 7)
    elif social > 0.55 and reward > 0.45:
        policy.humor_allowed = True
        policy.warmth_level = max(policy.warmth_level, 6)

    if reason > 0.55 and threat < 0.45:
        policy.question_policy = QuestionPolicy(True, 1, "clarifying", True)
        policy.certainty_style = CertaintyStyle.PROVISIONAL

    if state in {"Shutdown", "Retreating"}:
        policy.max_words = min(policy.max_words, 90)
        policy.max_chars_per_beat = min(policy.max_chars_per_beat, 150)
        policy.question_policy = QuestionPolicy(False, 0, "none", True)
        policy.ending_style = EndingStyle.SOFT_LANDING

    return policy
